services:
  init:
    build:
      dockerfile_inline: |
        FROM ubuntu:24.04
        COPY init.sh /init.sh
        RUN sed -i 's/\r//' /init.sh # Windows 対策
        CMD ["/bin/bash", "/init.sh"]
    volumes:
      - ./secrets:/secrets
    network_mode: "none"
  slack_dify:
    build:
      dockerfile_inline: |
        FROM python:3.12-slim
        RUN mkdir /app
        WORKDIR /app
        RUN apt update && apt upgrade -y
        COPY requirements.txt .
        RUN pip install -r requirements.txt
        COPY main.py .
        CMD ["python", "main.py"]
    volumes:
      - ./secrets:/secrets:ro
