services:
  init:
    build:
      dockerfile_inline: |
        FROM ubuntu:24.04
        COPY init.sh /init.sh
        CMD ["/bin/bash", "/init.sh"]
    volumes:
      - ./secrets:/secrets
  slack_dify:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secrets:/secrets:ro
